from .animal import Animal
from .anaconda import Anaconda
from .boa import Boa
from .cobra import Cobra
from .python import Python
from .snake import Snake
from .cat import Cat
from .dog import Dog
from .donkey import Donkey
from .llama import Llama
from .rabbit import Rabbit
from .clownfish import Clownfish
from .dolphin import Dolphin
from .goldfish import Goldfish
from .penguin import Penguin
from .seaturtle import Sea_Turtle
from .goose import Goose
